version: '3'
services:
  app:
    image: sose-cicd201
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27019:27017
